# dataset_size:
#   - 600
# dataset_size_test:
#   - 2000
# no_classes:
#   - 100
# no_classes_test:
#   - 10
# dimensions:
#   - 16
# mean_max:
#   - 5
# clusterCoef:
#   - 2
# no_clusters:
#   - 5
# use_train_anomalies:
#   - True #!!!!!!
# train_anomalies:
#   - 0.49
# test_anomalies:
#   - 0.1
# dataset_size:
#   - 30000
# dataset_size_test:
#   - 20000
# no_classes:
#   - 40
# no_classes_test:
#   - 10
# dimensions:
#   - 2
# mean_max:
#   - 5
# clusterCoef:
#   - 1.2 #3 a fost folosit pt reprezentarea tsne la random
# no_clusters:
#   - 5 #10
# use_train_anomalies:
#   - True #!!!!!!
# train_anomalies:
#   - 0.49
# test_anomalies:
#   - 0.2
# rotation:
#   - 180
# random:
#   - 1
dataset_size:
  - 1000
dataset_size_test:
  - 2000
no_classes:
  - 1 #20
no_classes_test:
  - 0
dimensions:
  - 4
mean_max:
  - 5
clusterCoef:
  - 1.4
no_clusters:
  - 10
use_train_anomalies:
  - True 
train_anomalies:
  - 0.15
test_anomalies:
  - 0.1
rotation:
  - 40
random:
  - 1